Resources:
  todoappuserpoolC22ED3C2:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      Schema:
        - Mutable: true
          Name: email
          Required: true
      SmsVerificationMessage: The verification code to your new account is {####}
      UserPoolName: todo-app-user-pool
      UsernameAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-user-pool/Resource
  todoappuserpoolclient81F878F3:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - profile
        - phone
        - email
        - openid
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://example.com
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId:
        Ref: todoappuserpoolC22ED3C2
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-user-pool-client/Resource
  todoapptodo88A5EC6F:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: todoId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: userIdCreatedAtIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: todoId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: Todo
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-todo/Resource
  todoapplambdaServiceRoleCFD3B80A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-lambda/ServiceRole/Resource
  todoapplambdaServiceRoleDefaultPolicy56797EBE:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - todoapptodo88A5EC6F
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - todoapptodo88A5EC6F
                        - Arn
                    - /index/*
        Version: "2012-10-17"
      PolicyName: todoapplambdaServiceRoleDefaultPolicy56797EBE
      Roles:
        - Ref: todoapplambdaServiceRoleCFD3B80A
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-lambda/ServiceRole/DefaultPolicy/Resource
  todoapplambdaCE6DDDEB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-ap-northeast-1
        S3Key: 60bd323a184fe6da978b053cffda982b00e614be01491d04b8ee697de6c8a7d4.zip
      Environment:
        Variables:
          COGNITO_USER_POOL_ID:
            Ref: todoappuserpoolC22ED3C2
          COGNITO_USER_POOL_CLIENT_ID:
            Ref: todoappuserpoolclient81F878F3
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - todoapplambdaServiceRoleCFD3B80A
          - Arn
      Runtime: nodejs18.x
      Timeout: 30
    DependsOn:
      - todoapplambdaServiceRoleDefaultPolicy56797EBE
      - todoapplambdaServiceRoleCFD3B80A
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-lambda/Resource
      aws:asset:path: /Users/shohei/project/todo_app/cdk-todo-app/cdk.out/asset.60bd323a184fe6da978b053cffda982b00e614be01491d04b8ee697de6c8a7d4
      aws:asset:is-bundled: true
      aws:asset:property: Code
  todoapprestapiF3D03277:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: todo-app-rest-api
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Resource
  todoapprestapiDeployment5ECDDF65ca02d78ce5c1540771da59ae4cb2fb0b:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: todoapprestapiF3D03277
    DependsOn:
      - todoapprestapiproxyANYDAD677C6
      - todoapprestapiproxy63FFFE4D
      - todoapprestapiANY5776FC1C
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Deployment/Resource
  todoapprestapiDeploymentStagev1139D5714:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: todoapprestapiDeployment5ECDDF65ca02d78ce5c1540771da59ae4cb2fb0b
      RestApiId:
        Ref: todoapprestapiF3D03277
      StageName: v1
      TracingEnabled: true
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/DeploymentStage.v1/Resource
  todoapprestapiproxy63FFFE4D:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - todoapprestapiF3D03277
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: todoapprestapiF3D03277
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Default/{proxy+}/Resource
  todoapprestapiproxyANYApiPermissionCdkTodoAppStacktodoapprestapiC56CB4A7ANYproxy2A7CFAB0:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - todoapplambdaCE6DDDEB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: todoapprestapiF3D03277
            - /
            - Ref: todoapprestapiDeploymentStagev1139D5714
            - /*/*
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Default/{proxy+}/ANY/ApiPermission.CdkTodoAppStacktodoapprestapiC56CB4A7.ANY..{proxy+}
  todoapprestapiproxyANYApiPermissionTestCdkTodoAppStacktodoapprestapiC56CB4A7ANYproxy81048063:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - todoapplambdaCE6DDDEB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: todoapprestapiF3D03277
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Default/{proxy+}/ANY/ApiPermission.Test.CdkTodoAppStacktodoapprestapiC56CB4A7.ANY..{proxy+}
  todoapprestapiproxyANYDAD677C6:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - todoapplambdaCE6DDDEB
                  - Arn
              - /invocations
      ResourceId:
        Ref: todoapprestapiproxy63FFFE4D
      RestApiId:
        Ref: todoapprestapiF3D03277
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Default/{proxy+}/ANY/Resource
  todoapprestapiANYApiPermissionCdkTodoAppStacktodoapprestapiC56CB4A7ANY5D2C7F42:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - todoapplambdaCE6DDDEB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: todoapprestapiF3D03277
            - /
            - Ref: todoapprestapiDeploymentStagev1139D5714
            - /*/
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Default/ANY/ApiPermission.CdkTodoAppStacktodoapprestapiC56CB4A7.ANY..
  todoapprestapiANYApiPermissionTestCdkTodoAppStacktodoapprestapiC56CB4A7ANYDEB7F55B:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - todoapplambdaCE6DDDEB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: todoapprestapiF3D03277
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Default/ANY/ApiPermission.Test.CdkTodoAppStacktodoapprestapiC56CB4A7.ANY..
  todoapprestapiANY5776FC1C:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - todoapplambdaCE6DDDEB
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - todoapprestapiF3D03277
          - RootResourceId
      RestApiId:
        Ref: todoapprestapiF3D03277
    Metadata:
      aws:cdk:path: CdkTodoAppStack/todo-app-rest-api/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/01QSW7DMAx8S+4Ki6RAl2OSoqcugdueA0VmXTqyaFhyU8PQ36vFMXKaITUzFLmGxztYL+TZLlV5Wmo6wvjhpDqJ0DqMiitDjmH8stjtmbXYfZuZX8hOExp3/ZQ7XpSDkQ2XIfRTHjVGSSJeaNkcS3kwXGJt4S3Bc2+UIzaCZANjwdmQcM+a1BDLzLywtwdpLToLmwihhm2vTui20uIUD2MwzKnRjF1D1obKC9lSJR2e5QDjS5IXaN2mpTR0ok/Yah6aab2rKhypSt/LJOi57xSm4fuO/4ZLZ0rL/BXdD5exlZn3s1OkNWIamSoq3nvX9u7a7kU8F9T25nf1AKt7WC1qS7TseuOoQSgy/gN8ZD/W1AEAAA==
    Metadata:
      aws:cdk:path: CdkTodoAppStack/CDKMetadata/Default
Outputs:
  todoapprestapiEndpointEFE3A3B6:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: todoapprestapiF3D03277
          - .execute-api.ap-northeast-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: todoapprestapiDeploymentStagev1139D5714
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

